version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: next-pwa
    versions:
    - 5.0.6
    - 5.1.4
    - 5.2.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 9.5.4
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
